services:
  web: # Flask app/ my BACEND with Flask “instruction book” framework 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ww_reeksamen_flask
    depends_on:
      - mariadb
    ports:
      - 80:80 # 0 - 1024 reserved. Use any port from 1025 to 65535
    volumes:
      - .:/app
    env_file:
      - .env
 
  mariadb: # the database (where all the actual data lives)
    image: mariadb:10.6.20
    container_name: ww_reeksamen_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ww_reeksamen
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3312:3306
 
  phpmyadmin: # the visual tool to inspect what's inside mariadb (only for me, the developer - not part of the app itself)
    image: phpmyadmin/phpmyadmin
    container_name: ww_reeksamen_phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8081:80
 
volumes:
  mariadb_data: